//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManHinhAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class next_question_led
    {
        public int id { get; set; }
        public Nullable<int> next_led_status { get; set; }
    }
}
