//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManHinhAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.answers_of_student = new HashSet<answers_of_student>();
        }
    
        public int id_question { get; set; }
        public string true_answer { get; set; }
        public Nullable<int> point { get; set; }
        public string name_question { get; set; }
        public byte[] img_question { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_topic { get; set; }
        public Nullable<int> id_question_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answers_of_student> answers_of_student { get; set; }
        public virtual question_topic question_topic { get; set; }
        public virtual question_type question_type { get; set; }
        public virtual statuss statuss { get; set; }
    }
}
