//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManHinhAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_next_question
    {
        public int id { get; set; }
        public Nullable<int> count_status_next_question { get; set; }
    }
}
